### ISSUE TITLE
로그인/ 회원가입 페이지 리팩토링

### ISSUE THREAD

**Issue by MinwooJe** [UMC-HeartHub/HeartHub-iOS#35]
## Description
중복 코드 제거
화면 전환 로직 짜기

## Todo
- [x] 중복 코드 제거
- [x] 화면 전환 로직 짜기
- [x] 키보드 올라올 때 뷰 올라가는 거 구현
- [x] 레이아웃 수정
- [x] 회원가입 페이지 체크박스 로직 구현

## Etc
기타사항 있으면 작성
